# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

import json

#open file generated by BabelEdit
lan_list=['en', 'de', 'es', 'fr', 'nl','ja', 'ko']
for lan in lan_list:
    with open('/home/xing/Repository/eval/i18n/Trans-6-14-19/'+ lan +'.json') as f:
        data=json.load(f)

    json_string=str(data)
    
    #replace {\'0\':  ...} with []
    
    str1="{\'0\':"
    n=0
    ind=[]
    for i in range(len(json_string)):
        n=json_string.find(str1,n+1,len(json_string))
        ind.append(n)
        if n==-1:
            break
    del ind[-1]
    
    jlist=list(json_string)
    for i in ind:
        m=json_string.find("}}",i)
        jlist[m+1]=']'
    json_string1="".join(jlist)
    
    s1=json_string1.replace(str1,'[')
    
    #replace \'1\' with ""
    si=s1
    for i in range (50):
        stri="\'"+str(i)+"\':"
        si=si.replace(stri,'')
    
    si_dict=eval(si)
    
    #save file
    with open('/home/xing/Repository/eval/i18n/' + lan +'.json','w') as fp:
        json.dump(si_dict,fp,ensure_ascii=False,indent=4)